spring:
  datasource:
    one:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.6.188:3306/springboot_db1
      username: root
      password: 123456
    two:
      driver-class-name: com.mysql.jdbc.Driver
      #需要注意 springboot2.0 url=>jdbc-url
      jdbc-url: jdbc:mysql://192.168.6.188:3306/springboot_db2
      username: root
      password: 123456
